### ISSUE TITLE
ssl configuration

### ISSUE THREAD

**Issue by getsachmail** [pnxtech/hydra-express#106]
Hi

Looking for ssl configuration with hydra, Is it possible to configure ssl certificates?

**Comment by cjus** [comment]
Hello @getsachmail, configure in what sense? Can you provide a detailed use case?

**Comment by getsachmail** [comment]
Need https end point on all microservices insted of http, As of now we have configure hydra-router as https service and all internal microservice as http which is working good for us.

**Comment by cjus** [comment]
@getsachmail thanks. closing this issue.
