### ISSUE TITLE
Usage with Node Cluster

### ISSUE THREAD

**Issue by gustavomassa** [pnxtech/hydra-express#115]
Hi,

Thanks for sharing this awesome library!

I'm starting migrating our node cluster application to microservices.
Our app uses express with node cluster, so we have 5+ workers running with express framework.

https://nodejs.org/api/cluster.html

1. How should I use hydra-express with node cluster module?
2. I want to use websocket as well, I did not find any examples of hydra with websocket, can hydra handle/route websocket request and server push notifications?

Thank you

**Comment by cjus** [comment]
@gustavomassa sorry for this super late reply - not sure how I missed this.  Did you ever work out a solution?  For examples on hydra / websockets see our hydra router: https://github.com/flywheelsports/hydra-router
