### ISSUE TITLE
Remove deprecated usage of Bunyan

### ISSUE THREAD

**Issue by cjus** [pnxtech/hydra-express#14]
These entries in the package.json files and any related code in index.js

```javascript    
     "bunyan": "1.8.4",
    "bunyan-loggly": "1.1.0",
    "bunyan-logstash-tcp": "0.3.4",
    "bunyan-prettystream": "0.1.3",
```

**Comment by miksansegundo** [comment]
Hi, thanks for this awesome work. I'll be happy to contribute because I'm gonna start to use it in my current project.

The error logging strategy looks nice, but what about error traces?

May I ask you what is your approach logging error traces?

**Comment by emadum** [comment]
Hi @miksansegundo, check out the logging plugin in the [fwsp-logger](https://github.com/flywheelsports/fwsp-logger) repository. It's based on the Pino logger and intended to work with Kibana/ElasticSearch. Pino handles error trace logging with a standard error serializer you can override with your own. 

If the fwsp-logger HydraExpressLogger plugin doesn't fit your needs, it should be pretty simple to make your own. Feel free to reach out with any questions!

**Comment by emadum** [comment]
Bunyan deps were removed in f85e415, closing.
