### ISSUE TITLE
HTTP-StatusCode 403

### ISSUE THREAD

**Issue by ghost** [pnxtech/hydra-express#86]
It seems that hydra can't handle the HTTP-StatusCode 403. Whenever I try to send this status it defaults to 503, which means the service is unavailable (which is not true).
The reason for this seems to be that the key '403' doesn't exist in the ServerResponse.STATUS-object in the server-response.js-file. Therefore the createResponseObject function throws an error (because it tries to access the object at a key that does not exist) and the response defaults to 503 in the catch-block of _tryAPIRequest.

Is there any workaround for this?

**Comment by drosi94** [comment]
Try to use 401 as workaround

**Comment by cjus** [comment]
@lfroe Will be reviewing your PR for this today. Thanks for that.

**Comment by cjus** [comment]
@lfroe I added an entry for HTTP 403 and your patch for any missing status codes. Please try hydra@1.4.8-experimental.3 or hydra-express@1.4.8-experimental.5

**Comment by cjus** [comment]
This is now present in hydra@1.4.8 and hydra-express@1.4.8.
